// AUTO-GENERATED by scripts/generate-skill-bundle.ts
// Do NOT edit manually — run `bun scripts/generate-skill-bundle.ts` to regenerate

export interface BundledSkillEntry {
  name: string;
  description: string;
  category: string;
  version: string;
  tools: string[];
  triggers: string[];
  body: string;
}

export const BUNDLED_SKILLS_DATA: BundledSkillEntry[] = [
  {
    name: "agent_spawner",
    description: `Create and manage specialized worker agents with optimal tool assignments and lifecycle control`,
    category: "agents",
    version: "1.1.0",
    tools: ["get_available_models","agent_find","agent_create","agent_archive"],
    triggers: ["creá un agente","create agent","creá un worker","create worker","nuevo agente","new agent","agente especializado","specialized agent","buscá un agente","find agent","archivá agente","archive agent","worker inactivo","inactive worker"],
    body: `
# Agent Spawner Skill

## Cuándo se Activa

Para crear nuevos workers especializados o gestionar el ciclo de vida de agents existentes.

> **Antes de crear nada**: la sección COLMENA DE AGENTES del system prompt ya lista workers listos para recibir trabajo (web, browser, archivos, código, Office, A2UI, cron y APIs). Crear un worker es el último recurso, excepto para MCP: si no existe un especialista del servidor, primero se pide autorización al usuario y luego se crea uno persistente.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`get_available_models\` | Consulta providers y modelos activos de la BD | **ANTES de crear** — seleccionar modelo óptimo |
| \`agent_find\` | Busca agents existentes | **PRIMERO** — antes de crear |
| \`agent_create\` | Crea nuevo worker | Si no existe apto |
| \`agent_archive\` | Archiva worker | Limpieza, inactivos |

## Workflow

### Crear Agent
1. **Buscar** → \`agent_find({ search })\` — ¿existe?
2. **Si existe** → Reutilizar
3. **Si no existe** → \`get_available_models({ capabilities })\` — seleccionar modelo óptimo
4. **Crear** → \`agent_create({...})\` con providerId y modelId seleccionados

Para MCP, incluí \`mcp_server_id\` y creá un agente por servidor. La tool rechaza duplicados y nunca debe llamarse antes de la confirmación del usuario.

### Create Agent Config
\`\`\`javascript
// 1. Consultar modelos disponibles para coding
get_available_models({ capabilities: "coding" })
// → [{ providerId: "openai", modelId: "gpt-4o", contextWindow: 128000 }, ...]

// 2. Crear agente con modelo óptimo (providerId y modelId son OBLIGATORIOS)
agent_create({
  name: "ai_coder",
  description: "Experto en código y refactorización",
  system_prompt: \`
    Sos desarrollador experto. Tu rol:
    1. Escribir código limpio y testeable
    2. Refactorizar código existente
    3. Revisar PRs y sugerir mejoras
  \`,
  tools_json: ["fs_read", "fs_write", "fs_edit", "cli_exec"],
  providerId: "openai",  // OBLIGATORIO - seleccionado de get_available_models
  modelId: "gpt-4o",     // OBLIGATORIO - seleccionado de get_available_models
  tone: "professional",
  max_iterations: 15
})
\`\`\`

## Mejores Prácticas

- **Buscar primero**: Nunca duplicar workers
- **Consultar modelos**: Usar \`get_available_models\` ANTES de crear para seleccionar provider/model óptimo
- **System prompt específico**: Enfocado en especialidad
- **Mínimo privilegio**: Solo tools necesarias
- **Nombres descriptivos**: Que indiquen propósito
- **Modelo adecuado**: Seleccionar según capacidad requerida (coding, chat, analysis, vision)

## Errores a Evitar

- ❌ Crear sin buscar primero
- ❌ Crear sin consultar modelos disponibles (\`get_available_models\`)
- ❌ Usar modelo inadecuado para la tarea (ej: modelo pequeño para coding complejo)
- ❌ Tools en exceso ("por las dudas")
- ❌ System prompt genérico
- ❌ Nombres vagos ("worker1", "agent1")
`,
  },
  {
    name: "memory_manager",
    description: `Complete management of persistent memory including write, read, search, list, and delete operations`,
    category: "agents",
    version: "1.0.0",
    tools: ["memory_write","memory_read","memory_list","memory_search","memory_delete"],
    triggers: ["guardá en memoria","save to memory","recordá esto","remember this","leé la memoria","read memory","qué hay en memoria","what's in memory","buscá en memoria","search memory","lista las memorias","list memories","eliminá de memoria","delete from memory","preferencias","preferences","datos persistentes","persistent data"],
    body: `
# Memory Manager Skill

## Cuándo se Activa

Para guardar, recuperar, buscar, listar o eliminar información persistente entre sesiones.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`memory_write\` | Almacena con título único | Guardar preferencias, datos |
| \`memory_read\` | Recupera por título exacto | Cuando conocés el título |
| \`memory_list\` | Lista todos los títulos | Explorar qué hay guardado |
| \`memory_search\` | Busca por keywords | Cuando no recordás título exacto |
| \`memory_delete\` | Elimina entrada | Limpiar datos obsoletos |

## Workflow

### Write
\`\`\`javascript
memory_write({ 
  title: "Preferencias de Desarrollo",
  content: "TypeScript, VS Code, Prettier single quotes"
})
\`\`\`

### Read/Search
\`\`\`javascript
memory_read({ title: "Preferencias" })  // Título exacto
memory_search({ query: "preferencias" })  // Fuzzy match
\`\`\`

### List
\`\`\`javascript
memory_list({})  // Todos los títulos
\`\`\`

### Delete
\`\`\`javascript
memory_delete({ title: "Datos Temporales" })
\`\`\`

## Mejores Prácticas

- Títulos descriptivos y únicos
- Agrupar datos relacionados en misma entrada
- Confirmar antes de sobrescribir
- No guardar datos sensibles

## Errores a Evitar

- ❌ Datos sensibles (passwords, API keys)
- ❌ Títulos genéricos ("Config", "Datos")
- ❌ Sobrescribir sin confirmar
- ❌ Entradas gigantes (split por tema)
`,
  },
  {
    name: "research_and_remember",
    description: `Research information from web sources and save findings to persistent memory`,
    category: "agents",
    version: "1.0.0",
    tools: ["web_search","web_fetch","memory_write"],
    triggers: ["investigá y guardá","research and save","buscá y recordá","find and remember","aprendé sobre","learn about","estudiá esto","study this","documentate y guardá","research and store"],
    body: `
# Research and Remember Skill

## Cuándo se Activa

Para investigar temas en la web y guardar el conocimiento sintetizado en memoria persistente.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`web_search\` | Busca en internet | Encontrar fuentes |
| \`web_fetch\` | Descarga contenido | Obtener detalles |
| \`memory_write\` | Guarda conocimiento | Almacenar para futuro |

## Workflow

1. **Buscar** → \`web_search({ query, numResults: 8 })\`
2. **Fetch** → \`web_fetch({ urls: top 2-3 })\`
3. **Sintetizar** → Compilar hallazgos con estructura clara
4. **Guardar** → \`memory_write({ title, content })\`

## Estructura de Conocimiento

\`\`\`markdown
# {Topic}

## Summary
2-3 oración resumen

## Key Findings
- Punto clave 1
- Punto clave 2
- ...

## Sources
- [Source 1](url)
- [Source 2](url)
\`\`\`

## Mejores Prácticas

- Mínimo 2 searches para cobertura completa
- Cruzar información entre fuentes múltiples
- Incluir URLs para verificación
- Estructura clara con headings
- Flaggear información incierta

## Errores a Evitar

- ❌ Una sola búsqueda (insuficiente)
- ❌ Sin fuentes (no verificable)
- ❌ Títulos vagos para memoria
- ❌ No flaggear información conflictiva
`,
  },
  {
    name: "task_orchestrator",
    description: `Orchestrate tasks across multiple workers with delegation, status tracking, and bus communication`,
    category: "agents",
    version: "1.2.0",
    tools: ["get_available_models","task_delegate","task_list","task_status","agent_find","agent_create","bus_publish","bus_read"],
    triggers: ["delegá esta tarea","delegate task","orquestá los workers","orchestrate workers","coordiná el equipo","coordinate team","estado de las tareas","task status","comunicá los workers","communicate workers","mensaje al bus","bus message","tarea en paralelo","parallel tasks"],
    body: `# Task Orchestrator — referencia operativa

La doctrina de orquestación (descomponer → delegar en paralelo → terminar el turno → sintetizar en el fan-in) está en tu system prompt. Esta skill es la referencia de las herramientas.

## Herramientas

| Tool | Qué hace | Cuándo |
|------|----------|--------|
| \`task_delegate\` | Persiste y asigna una tarea a un worker | Delegar. Preferí \`mode="async"\` |
| \`agent_find\` | Descubre workers del catálogo y propios | Antes de delegar. Nunca para comprobar ejecución |
| \`task_list\` | Lista ejecuciones reales persistidas | El usuario pregunta y no conocés IDs |
| \`task_status\` | Estado de tareas por ID | El usuario pide estado antes del fan-in |
| \`get_available_models\` | Providers y modelos activos | Antes de crear un worker |
| \`agent_create\` | Crea un worker nuevo | Último recurso: nada del catálogo sirve |
| \`bus_publish\` / \`bus_read\` | Mensajes entre workers | Dependencias entre workers en vuelo |

## Fan-out

\`\`\`javascript
// Tres partes independientes → tres llamadas en la MISMA respuesta
task_delegate({ worker_id: "web_researcher",            task_description: "...", mode: "async" })
task_delegate({ worker_id: "office_document_agent",     task_description: "...", mode: "async" })
task_delegate({ worker_id: "schedule_automation_agent", task_description: "...", mode: "async" })
\`\`\`

Cada llamada devuelve \`task_id\`, \`job_id\` y \`run_id\`: prueba de que la tarea quedó persistida.

## Fan-in

Hive te reinvoca con:

\`\`\`
[Sistema] Todas las tareas delegadas de este turno alcanzaron estado terminal.
[{ task_id, worker_id, task, ok, result, error }, ...]
\`\`\`

Sintetizá una sola respuesta. Las entradas con \`ok: false\` se reportan con su motivo real.

## Crear un worker (último recurso)

\`\`\`javascript
get_available_models({ capabilities: "analysis" })
// → [{ providerId: "anthropic", modelId: "claude-sonnet-4-6", ... }]

agent_create({
  name: "data_analyst",
  description: "Experto en análisis de datos",
  system_prompt: "Sos analista de datos experto...",
  tools_json: ["web_search", "web_fetch", "save_note"],
  providerId: "anthropic",   // OBLIGATORIO
  modelId: "claude-sonnet-4-6", // OBLIGATORIO
})
\`\`\`

Para una integración MCP sin especialista, pedí autorización primero. Si el usuario acepta, creá un worker con \`mcp_server_id\`; si participan varios servidores, creá o reutilizá uno por servidor. Nunca pases servidores MCP dinámicos a \`task_delegate\`.

## Errores a evitar

- ❌ Serializar tareas independientes en vez de fan-out paralelo
- ❌ Polling con \`task_status\` esperando el resultado — el fan-in llega solo
- ❌ Declarar éxito antes de recibir el \`[Sistema]\`, o presentar \`ok=false\` como éxito
- ❌ Reportar éxito sin revisar \`acceptance\`/\`checks\` de la entrega, o ignorar un \`checks.status="failed"\`
- ❌ Corregir a mano lo que \`task_revise\` puede reencolar en el mismo worker
- ❌ Crear un worker que el catálogo ya cubre
- ❌ Delegar saludos, preguntas simples o la conversación
- ❌ Usar \`delegate_task\`, \`find_agent\`, \`create_agent\`, \`get_task_status\`, \`publish_to_bus\`, \`get_bus_messages\` — **no existen**
`,
  },
  {
    name: "cli_pipeline",
    description: `Execute shell commands and pipe output to files for logging and further processing`,
    category: "cli",
    version: "1.0.0",
    tools: ["cli_exec","fs_write"],
    triggers: ["guardá el output","save output","pipeline","pipe to file","redireccioná el output","redirect output","log del comando","command log","ejecutá y guardá","run and save","resultado en archivo","result to file"],
    body: `
# CLI Pipeline Skill

## Cuándo se Activa

Para ejecutar comandos y guardar el output en archivos para logging o procesamiento posterior.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`cli_exec\` | Ejecuta un comando con timeout y captura su salida | Comandos autorizados |
| \`fs_write\` | Escribe un archivo dentro del workspace | Guardar output |

## Workflow

1. **Validar comando** → Seguro para ejecución
2. **Ejecutar** → Capturar stdout + stderr
3. **Formatear** → Agregar timestamp, comando, metadata
4. **Escribir** → \`fs_write({ path, content })\`

## Formato de Log

\`\`\`markdown
# Command Log

**Command**: npm install
**Timestamp**: 2025-03-09 14:30:00
**Exit Code**: 0
**Execution Time**: 45.2s

---

## Output

[stdout content...]
[stderr if any...]
\`\`\`

## Mejores Prácticas

- Filenames con timestamp para tracking
- Incluir metadata completa (exitCode, tiempo)
- Capturar stdout y stderr
- Para outputs grandes, escribir incrementalmente

## Errores a Evitar

- ❌ No incluir metadata en log
- ❌ Filenames genéricos sin timestamp
- ❌ No capturar stderr
`,
  },
  {
    name: "cli_safe_exec",
    description: `Execute shell commands safely with error handling, timeouts, and output validation`,
    category: "cli",
    version: "1.0.0",
    tools: ["cli_exec"],
    triggers: ["ejecutá este comando","run this command","corré el comando","execute command","terminal","bash","shell","npm","yarn","bun","git","docker","comando de sistema","system command"],
    body: `
# CLI Safe Exec Skill

## Cuándo se Activa

Para ejecutar comandos de shell de forma segura con manejo de errores y timeouts.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`exec\` | Ejecuta con validación y timeout | Comandos simples (<30s) |
| \`terminal\` | Ejecuta con entorno completo | Comandos complejos, Git, npm |

## ⚠️ ADVERTENCIA CRÍTICA

**NUNCA usar para tareas programadas** — usar \`cron.create\` en su lugar.

## Workflow

1. **Validar** → Comando es seguro, no destructivo
2. **Ejecutar** → \`exec\` o \`terminal\` con timeout apropiado
3. **Parsear** → Check exitCode, stdout, stderr
4. **Manejar error** → Si falló, analizar y sugerir fixes

## Timeouts Apropiados

| Tipo | Timeout |
|------|---------|
| Listar archivos | 10s |
| Git operations | 30s |
| npm install | 120s |
| npm run build | 120s |
| npm test | 180s |
| Docker builds | 300s |

## Errores a Evitar

- ❌ Usar para cron (usar cron.create)
- ❌ Sin timeout apropiado
- ❌ Ignorar exitCode
- ❌ Comandos destructivos sin confirmar
`,
  },
  {
    name: "software_engineering",
    description: `Implement, debug, and verify scoped software changes in an existing repository`,
    category: "cli",
    version: "1.0.0",
    tools: ["fs_read","fs_write","fs_edit","fs_list","fs_glob","fs_exists","cli_exec"],
    triggers: ["implementar código","corregir bug","ejecutar tests","implement code","fix bug"],
    body: `
# Ingeniería de software

1. Inspecciona estructura, convenciones y cambios existentes.
2. Determina la causa o el cambio mínimo antes de editar.
3. Conserva cambios ajenos y limita el diff al objetivo.
4. Ejecuta tests, typecheck o build proporcionales al riesgo.
5. Entrega archivos cambiados, comandos ejecutados, resultados y riesgos.

No publiques, no delegues y no uses comandos destructivos sin autorización explícita.
`,
  },
  {
    name: "cron_manager",
    description: `Manage Hive scheduled automations. Create, list, update, pause, resume, delete, trigger, and inspect recurring or one-shot jobs.`,
    category: "cron",
    version: "2.0.0",
    tools: ["cron.create","cron.list","cron.update","cron.delete","cron.pause","cron.resume","cron.trigger","cron.history"],
    triggers: ["programá una tarea","schedule task","creá un cron","create cron","editá el cron","edit cron","eliminá el cron","remove cron","lista las tareas","list cron jobs","modificá el cron","modify cron","tarea recurrente","recurring task","todos los días","daily","cada semana","weekly"],
    body: `
# Cron Manager Skill

## Cuándo se Activa

Para gestionar tareas programadas (cron jobs): crear, listar, actualizar, pausar, reanudar, eliminar, ejecutar y ver historial.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`cron.create\` | Crear cron job | Nueva tarea |
| \`cron.list\` | Listar todos | Ver existentes |
| \`cron.update\` | Actualizar existente | Cambiar horario/instrucción |
| \`cron.pause\` | Pausar temporalmente | Sin eliminar |
| \`cron.resume\` | Reanudar pausado | Continuar ejecución |
| \`cron.delete\` | Eliminar permanentemente | Cancelar para siempre |
| \`cron.trigger\` | Ejecutar ahora | Forzar ejecución |
| \`cron.history\` | Ver historial | Ver logs de ejecuciones |

## Campos Principales

| Campo | Tipo | Descripción |
|-------|------|-------------|
| \`name\` | string | Identificador corto (e.g., 'daily-report') |
| \`task\` | string | **REQUERIDO** - Instrucciones para el agente al ejecutarse |
| \`task_type\` | string | 'recurring' (repite) o 'one_shot' (una vez) |
| \`cron_expression\` | string | Expresión cron (solo para recurring) |
| \`fire_at\` | string | Datetime ISO (solo para one_shot) |
| \`channel\` | string | Canal de notificación |
| \`start_at\` | string | Inicio de ventana opcional |
| \`stop_at\` | string | Fin de ventana opcional |
| \`dom_and_dow\` | number | 0=OR (default), 1=AND (día mes + día semana) |
| \`max_runs\` | number | Deja de correr después de N corridas ("recordámelo 3 veces") |
| \`payload\` | object | Datos que recibe el agente al ejecutarse |
| \`agent_id\` | string | Agente concreto que debe ejecutarla. Si se omite, decide el coordinador |
| \`tool_name\` | string | Ejecutar una tool directamente, sin pasar por un agente |

> **La zona horaria no se pasa acá**: sale del perfil del usuario. No la
> inventes ni la pidas — si el usuario dice "a las 9", son las 9 de su reloj.

## Cron Expression Format

\`\`\`
┌───────── segundos (0-59)  ← opcional, sólo si hacen falta
│ ┌─────── minuto (0-59)
│ │ ┌───── hora (0-23)
│ │ │ ┌─── día del mes (1-31)
│ │ │ │ ┌─ mes (1-12 o JAN-DEC)
│ │ │ │ │ ┌ día de semana (0-7 o SUN-SAT, 0 y 7 = domingo)
* * * * * *
\`\`\`

Cinco campos, o seis poniendo los segundos adelante. Acepta \`*\`, listas \`1,15\`,
rangos \`1-5\`, pasos \`*/2\`, y nombres de mes y de día.

## Ejemplos Comunes

| Expresión | Significado |
|-----------|-------------|
| \`0 9 * * *\` | Diario 9:00 AM |
| \`0 7 * * 1-5\` | Lun-Vie 7:00 AM |
| \`0 */2 * * *\` | Cada 2 horas |
| \`0 0 * * 0\` | Domingos medianoche |
| \`0 0 1 * *\` | Día 1 de cada mes |

## Cómo Usar start_at / stop_at

- \`start_at\`: La tarea no ejecuta antes de esta fecha
- \`stop_at\`: La tarea no ejecuta después de esta fecha
- Formato ISO: \`'2026-04-01T00:00:00'\`

## Cómo Usar dom_and_dow

- \`0\` (default): Se ejecuta si es el día del mes O el día de semana
- \`1\`: Se ejecuta solo si es EL MISMO día del mes Y el día de semana

Ejemplo: \`0 9 15 * *\` con dom_and_dow=1 significa "los 15 de cada mes QUE SEA domingo"

## Workflow para Crear

1. **Preguntar** → ¿one_shot o recurring?
2. **Obtener** → Hora y canal de notificación
3. **Crear** → \`cron.create\` con campo \`task\` obligatorio
4. **Confirmar** → \`cron.list\` mostrar next runs

## Errores a Evitar

- ❌ Olvidar el campo \`task\` — es obligatorio
- ❌ Usar exec para tareas programadas
- ❌ No preguntar si es one_shot o recurring
- ❌ No mostrar próximos horarios al crear
- ❌ Llamar \`cron.update\` sin \`task_id\` — siempre hacer \`cron.list\` primero
`,
  },
  {
    name: "cron_reminder",
    description: `Schedule a reminder for yourself at a specific time. Creates a one_shot cron job that sends a notification message via your preferred channel.`,
    category: "cron",
    version: "2.0.0",
    tools: ["cron.create","notify"],
    triggers: ["recordame","remind me","recordatorio","reminder","alerta","alert","avísame","notify me","programá","schedule","para mañana","for tomorrow","en 30 minutos","in 30 minutes"],
    body: `
# Cron Reminder Skill

## Cuándo se Activa

Para crear recordatorios de una sola ejecución (one_shot): "recuerdame a las 3pm", "avísame en 30 minutos", etc.

## Herramientas

| Tool | Qué hace |
|------|----------|
| \`cron.create\` | Crear recordatorio one_shot |
| \`notify\` | Enviar notificación directa |

## Cómo Funciona

1. **Preguntar** → ¿De qué te aviso? ¿A qué hora? ¿Por qué canal?
2. **Crear** → \`cron.create\` con \`task_type: 'one_shot'\` y \`fire_at\` en formato ISO
3. **Confirmar** → Mostrar hora programada

## Parámetros

| Campo | Descripción |
|-------|-------------|
| \`task\` | **REQUERIDO** - Mensaje del recordatorio |
| \`task_type\` | Siempre \`'one_shot'\` |
| \`fire_at\` | Fecha/hora ISO (ej: \`'2026-04-20T15:00:00'\`) |
| \`channel\` | Canal (telegram, discord, whatsapp, webchat) |

## Errores Comunes

- ❌ Olvidar el campo \`task\` — obligatorio para que el agente sepa qué enviar
- ❌ Usar expresiones cron para recordatorios (usar \`fire_at\` en vez de \`cron_expression\`)
- ❌ Poner \`fire_at\` en el pasado
`,
  },
  {
    name: "file_manager",
    description: `Explore project structure and locate files using glob patterns and directory listing`,
    category: "filesystem",
    version: "1.0.0",
    tools: ["fs_list","fs_glob","fs_exists"],
    triggers: ["lista los archivos","list files","buscá archivos","find files","explorá el proyecto","explore project","qué archivos hay","what files exist","buscá por patrón","search by pattern","existe este archivo","file exists","dónde está","where is"],
    body: `
# File Manager Skill

## Cuándo se Activa

Esta skill se activa cuando el usuario necesita:
- Explorar la estructura del proyecto
- Buscar archivos por extensión o patrón
- Verificar si existe un archivo o directorio
- Encontrar la ubicación de un archivo

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`fs_list\` | Lista directorios y archivos | Exploración inicial |
| \`fs_glob\` | Busca archivos por patrón wildcard | Búsqueda por extensión/patrón |
| \`fs_exists\` | Verifica existencia | Pre-check antes de operaciones |

## Workflow

1. **Explorar** → \`fs_list({ path })\` para estructura general
2. **Buscar por patrón** → \`fs_glob({ pattern })\` para tipos específicos
3. **Verificar** → \`fs_exists({ path })\` para confirmación

## Patrones Glob Comunes

| Patrón | Encuentra |
|--------|-----------|
| \`**/*.ts\` | Todos los TypeScript |
| \`**/*.test.ts\` | Solo tests |
| \`**/*.md\` | Documentación |
| \`**/package.json\` | Todos los package.json |
| \`src/**/*.tsx\` | React components en src |

## Errores a Evitar

- ❌ No verificar existencia antes de leer/editar
- ❌ Usar fs_list cuando se conoce el patrón (usar glob)
- ❌ Patrones muy amplios sin filtrado
`,
  },
  {
    name: "file_read_and_summarize",
    description: `Read and understand file content with automatic summarization for large files`,
    category: "filesystem",
    version: "1.0.0",
    tools: ["fs_read","fs_exists"],
    triggers: ["leé este archivo","read this file","mostrame el contenido","show content","qué dice este archivo","resumí este archivo","summarize this file","entendé este código","understand this code"],
    body: `
# File Read and Summarize Skill

## Cuándo se Activa

Esta skill se activa cuando el usuario necesita leer y entender el contenido de un archivo, especialmente cuando:
- El archivo es grande y necesita resumen
- Se requiere comprensión del contenido (no solo lectura)
- El usuario pide "qué dice", "resumí", "entendé"

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`fs_exists\` | Comprueba que el path exista | Antes de leer |
| \`fs_read\` | Lee contenido de archivo del workspace | Lectura de cualquier archivo |

## Workflow

1. **Verificar existencia** → \`fs_exists({ path })\`
2. **Leer contenido** → \`fs_read({ path, offset, limit })\`
3. **Sintetizar** → Resumir si es grande, extraer puntos clave

## Mejores Prácticas

- Para archivos >1000 líneas, usar \`offset\` y \`limit\`
- Identificar tipo de archivo por extensión y adaptar formato de resumen
- Para código: identificar funciones, clases, exports principales
- Para config: explicar settings clave en lenguaje simple
- Para texto: extraer ideas principales

## Errores a Evitar

- ❌ Leer sin verificar existencia
- ❌ Retornar archivo completo sin resumir si es muy grande
- ❌ No identificar tipo de archivo para adaptar resumen
`,
  },
  {
    name: "file_writer",
    description: `Create, modify, and delete files with safe edit operations after required authorization`,
    category: "filesystem",
    version: "1.0.0",
    tools: ["fs_read","fs_write","fs_edit","fs_exists"],
    triggers: ["creá un archivo","create a file","escribí en","write to","editá este archivo","edit this file","modificá","modify","eliminá el archivo","delete file","guardá esto","save this","actualizá el archivo","update file"],
    body: `
# File Writer Skill

## Cuándo se Activa

Esta skill se activa cuando el usuario necesita:
- Crear nuevos archivos
- Modificar contenido existente
- Eliminar archivos
- Guardar cambios

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`fs_read\` | Lee archivo existente | Antes de editar para entender estructura |
| \`fs_write\` | Crea o sobreescribe archivo | Archivos nuevos o reescritura completa |
| \`fs_edit\` | Edita secciones específicas | Cambios puntuales (find/replace) |
| \`fs_exists\` | Verifica existencia | Para decidir crear vs editar |

## Workflow

### Crear Archivo Nuevo
1. \`fs_exists({ path })\` → verificar no existe
2. \`fs_write({ path, content })\` → crear

### Editar Archivo Existente
1. \`fs_exists({ path })\` → verificar existe
2. \`fs_read({ path })\` → entender estructura
3. \`fs_edit({ path, old_string, new_string })\` → modificar
4. Ejecutar únicamente dentro del alcance autorizado por el coordinador

### Eliminar Archivo
1. \`fs_exists({ path })\` → verificar existe
2. Verificar que el coordinador ya obtuvo autorización explícita
3. \`fs_delete({ path })\`

## Mejores Prácticas

- **Leer antes de editar**: Nunca modificar sin entender estructura
- **Edit vs Write**: Usar edit para cambios pequeños, write para nuevos archivos
- **Respetar autorización**: las confirmaciones se gestionan previamente desde el panel interactivo
- **Paths seguros**: Trabajar dentro del workspace por defecto

## Errores a Evitar

- ❌ Editar sin leer primero
- ❌ Ampliar el alcance autorizado
- ❌ Eliminar sin autorización explícita previa
- ❌ Usar write cuando edit es suficiente
`,
  },
  {
    name: "workspace_file_operator",
    description: `Safely create, read, edit, organize, and verify files or folders inside an authorized workspace`,
    category: "filesystem",
    version: "1.0.0",
    tools: ["fs_read","fs_write","fs_edit","fs_delete","fs_list","fs_glob","fs_exists"],
    triggers: ["crear carpeta","organizar archivos","editar archivo","create folder","manage files"],
    body: `
# Operación segura del workspace

1. Resuelve todas las rutas contra el workspace asignado.
2. Comprueba el estado inicial con \`fs_exists\`, \`fs_list\` o \`fs_read\`.
3. Aplica la operación mínima solicitada.
4. Verifica el estado final mediante readback.

Nunca accedas fuera del workspace ni declares éxito basándote solo en el resultado de una escritura.
`,
  },
  {
    name: "office_document_manager",
    description: `Leer, crear y manipular archivos Office (PDF, Word, Excel, PowerPoint) desde el workspace`,
    category: "office",
    version: "1.0.0",
    tools: ["office_leer_pdf","office_escribir_pdf","office_leer_docx","office_escribir_docx","office_leer_xlsx","office_escribir_xlsx","office_leer_pptx","office_escribir_pptx"],
    triggers: ["leer pdf","abrir pdf","extraer texto de pdf","pdf a texto","crear pdf","generar pdf","exportar a pdf","leer word","abrir docx","extraer texto de word","crear word","generar docx","documento word","leer excel","abrir xlsx","datos de excel","crear excel","generar xlsx","exportar a excel","leer powerpoint","abrir pptx","presentacion","diapositivas","crear presentacion","generar pptx","read pdf","open pdf","create pdf","read excel","create excel","read word","create word","read powerpoint","create presentation"],
    body: `
# Office Document Manager Skill

## Cuándo se Activa

Esta skill se activa cuando el usuario necesita:
- **Leer** archivos PDF, Word (.docx), Excel (.xlsx) o PowerPoint (.pptx)
- **Generar** nuevos archivos en cualquiera de esos formatos
- **Convertir** contenido entre formatos (ej: texto → PDF, JSON → Excel)
- **Extraer** datos estructurados de documentos (tablas de Excel, slides de presentación)

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`office_leer_pdf\` | Extrae texto + metadata de PDF | Leer informes, contratos, libros en PDF |
| \`office_escribir_pdf\` | Genera PDF desde texto | Crear reportes, resúmenes, documentación |
| \`office_leer_docx\` | Extrae texto y tablas de Word | Leer documentos, contratos, informes Word |
| \`office_escribir_docx\` | Genera Word con estructura | Crear documentos formales con títulos/tablas |
| \`office_leer_xlsx\` | Lee hojas de Excel como JSON | Procesar datos, tablas, inventarios |
| \`office_escribir_xlsx\` | Genera Excel desde JSON | Exportar datos, crear reportes tabulares |
| \`office_leer_pptx\` | Extrae texto de cada slide | Resumir presentaciones, extraer contenido |
| \`office_escribir_pptx\` | Genera presentación PowerPoint | Crear slides desde datos o resúmenes |

## Workflow por Caso de Uso

### Leer y resumir un documento
1. \`office_leer_pdf/docx/xlsx/pptx\` → extraer contenido
2. Procesar y resumir el texto
3. \`notify\` → enviar resumen al usuario

### Transformar datos a Excel
1. Obtener datos (de memoria, herramienta o cálculo)
2. Estructurar en \`hojas\` con \`datos\` como array de objetos
3. \`office_escribir_xlsx\` → generar archivo
4. Confirmar ruta al usuario

### Crear un informe PDF
1. Compilar el contenido del informe como texto
2. \`office_escribir_pdf\` → generar con título y márgenes
3. Confirmar que el archivo quedó en la ruta esperada

### Generar una presentación
1. Definir estructura: título + array de slides (título + puntos)
2. \`office_escribir_pptx\` → generar .pptx
3. Opcional: incluir notas del presentador en cada slide

## Parámetros Clave

### \`parrafos\` para DOCX
\`\`\`json
[
  { "texto": "Capítulo 1", "tipo": "titulo1" },
  { "texto": "Subtítulo", "tipo": "titulo2" },
  { "texto": "Contenido normal", "tipo": "parrafo" },
  { "texto": "Ítem de lista", "tipo": "lista" },
  { "texto": "Texto importante", "tipo": "parrafo", "negrita": true }
]
\`\`\`

### \`hojas\` para XLSX
\`\`\`json
[
  {
    "nombre": "Ventas",
    "datos": [
      { "Mes": "Enero", "Total": 5000 },
      { "Mes": "Febrero", "Total": 6200 }
    ]
  }
]
\`\`\`

### \`diapositivas\` para PPTX
\`\`\`json
[
  {
    "titulo": "¿Qué es Machine Learning?",
    "puntos": ["Subcampo de IA", "Aprende de datos", "Hace predicciones"],
    "notas": "Mencionar el enfoque supervisado y no supervisado"
  }
]
\`\`\`

## Errores a Evitar

- ❌ Intentar leer un archivo que no existe (verifica con \`fs_exists\` primero)
- ❌ Sobrescribir sin confirmar cuando el archivo destino ya existe
- ❌ Usar \`contenido\` y \`puntos\` a la vez en PPTX — \`puntos\` tiene prioridad
- ❌ Pasar un array de arrays como \`datos\` de XLSX cuando se esperan objetos con claves
- ❌ Intentar leer PDF de más de 100 páginas sin especificar rango (usar \`pagina_inicio\`/\`pagina_fin\`)
`,
  },
  {
    name: "browser_automate",
    description: `Automate web workflows with navigation, clicks, form filling, and visual verification`,
    category: "web",
    version: "1.0.0",
    tools: ["browser_navigate","browser_wait","browser_click","browser_type","browser_screenshot","browser_script","computer_use_task"],
    triggers: ["automatizá el navegador","automate browser","completá el formulario","fill form","hacé clic en","click on","iniciá sesión","login","registrate","sign up","interactuá con la web","interact with website","flujo web","web workflow"],
    body: `
# Browser Automate Skill

## Cuándo se Activa

Esta skill se activa para automatizar flujos de interacción con aplicaciones web: logins, formularios, navegación programática.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`browser_navigate\` | Navega a URL | Inicio de flujo |
| \`browser_click\` | Click en elementos | Botones, enlaces, triggers |
| \`browser_type\` | Escribe en inputs | Formularios, búsquedas |
| \`browser_screenshot\` | Captura estado | Verificación visual |

## Workflow Típico

1. **Navegar** → URL inicial
2. **Interactuar** → click/type según flujo
3. **Verificar** → screenshot después de acciones críticas
4. **Repetir** → para flujos multi-paso

## Mejores Prácticas

- Selectores estables (IDs > classes > XPath)
- Esperar carga después de navegación
- Verificar estado visual con screenshots
- Manejar errores de elementos no encontrados

## Errores a Evitar

- ❌ Selectores frágiles que cambian
- ❌ No esperar carga de página
- ❌ Ignorar errores de elementos
- ❌ No verificar estado después de acciones
`,
  },
  {
    name: "browser_scrape",
    description: `Navigate to web pages and capture rendered content including screenshots for dynamic sites`,
    category: "web",
    version: "1.0.0",
    tools: ["browser_navigate","browser_screenshot","browser_extract","browser_wait"],
    triggers: ["capturá el contenido","scrape content","obtené la página renderizada","get rendered page","sitios dinámicos","dynamic sites","web con javascript","javascript websites","tomá screenshot y contenido","screenshot and content"],
    body: `
# Browser Scrape Skill

## Cuándo se Activa

Esta skill se activa para sitios web dinámicos que requieren JavaScript rendering, donde el contenido no está disponible en HTML estático.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`browser_navigate\` | Navega y renderiza página completa | Sitios con JavaScript/SPA |
| \`browser_screenshot\` | Captura estado visual | Evidencia de contenido renderizado |
| \`browser_extract\` | Extrae del DOM ya renderizado | Contenido textual o estructurado del SPA |
| \`browser_wait\` | Espera a que aparezca un selector | Antes de extraer, en páginas que cargan por partes |

> **No usar \`web_fetch\` acá.** Vuelve a pedir la URL al servidor y recibe el HTML
> sin JavaScript ejecutado — en un SPA, una cáscara vacía. Para eso está
> \`browser_extract\`, que lee el DOM que el navegador ya renderizó.

## Workflow

1. **Navegar** → \`browser_navigate({ url })\` + esperar renderizado JS
2. **Capturar visual** → \`browser_screenshot()\`
3. **Extraer texto** → \`web_fetch()\`
4. **Combinar** → screenshot + texto para scrape completo

## Mejores Prácticas

- Esperar renderizado completo de JavaScript
- Para infinite scroll: hacer scroll y múltiples screenshots
- Capturar antes y después de interacciones si es dinámico

## Errores a Evitar

- ❌ No esperar renderizado JavaScript
- ❌ Solo capturar HTML estático para sitios SPA
- ❌ Ignorar términos de servicio del sitio
`,
  },
  {
    name: "web_monitor",
    description: `Monitor changes in web sources and track updates over time with persistent memory`,
    category: "web",
    version: "1.0.0",
    tools: ["web_search","web_fetch","memory_write","memory_read"],
    triggers: ["monitoreá","monitor","seguí los cambios","track changes","avisame si cambia","notify if changes","actualización de","update on","novedades de","news about","cambios en","changes in"],
    body: `
# Web Monitor Skill

## Cuándo se Activa

Esta skill se activa cuando el usuario necesita:
- Monitorear cambios en una URL específica
- Recibir notificaciones de actualizaciones
- Seguir novedades sobre un tema
- Trackear evolución de contenido

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`web_fetch\` | Descarga contenido de URL | Obtener contenido actual |
| \`web_search\` | Busca novedades | Monitoreo por tema (no URL fija) |
| \`memory_write\` | Guarda baseline | Almacenar contenido para comparación |
| \`memory_read\` | Recupera baseline anterior | Comparar con contenido actual |

## Workflow

1. **Primera ejecución**: \`web_fetch\` → \`memory_write\` (baseline)
2. **Chequeos siguientes**: \`memory_read\` → \`web_fetch\` → comparar → \`notify\` si cambia
3. **Actualizar baseline**: \`memory_write\` con nuevo contenido

## Mejores Prácticas

- Ignorar cambios menores (timestamps, ads, contenido dinámico irrelevante)
- Notificar solo cambios significativos
- Para monitoreo periódico, combinar con \`cron.create\`

## Errores a Evitar

- ❌ No almacenar baseline inicial
- ❌ Notificar por cambios triviales
- ❌ No actualizar timestamp de baseline
`,
  },
  {
    name: "web_research",
    description: `Search and synthesize information from multiple web sources into structured reports`,
    category: "web",
    version: "1.0.0",
    tools: ["web_search","web_fetch"],
    triggers: ["investigá sobre","research","buscá información de","find information about","qué es","what is","explicame","explain","últimos avances","latest advances","tendencias de","trends in","información actualizada","current information"],
    body: `
# Web Research Skill

## Cuándo se Activa

Esta skill se activa cuando el usuario necesita información actualizada de internet, verificar datos, o investigar temas específicos.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`web_search\` | Busca en internet, devuelve títulos, URLs, snippets | Búsqueda inicial, encontrar fuentes |
| \`web_fetch\` | Descarga contenido completo de URL (HTML→Markdown) | Profundizar en resultados específicos |

## Workflow

1. **Búsqueda inicial** → \`web_search({ query, numResults: 8 })\`
2. **Fetch contenido** → \`web_fetch({ urls: top 2-3 })\`
3. **Búsqueda complementaria** → Segundo search si hay gaps
4. **Síntesis** → summary + key points + sources

## Mejores Prácticas

- Queries específicos (máx 6 palabras)
- Mínimo 2-3 fuentes independientes
- Priorizar contenido reciente (<1 año)
- Citas con URLs completas

## Errores a Evitar

- ❌ Inventar datos no encontrados
- ❌ Concluir con una sola búsqueda
- ❌ No verificar fecha de fuentes
- ❌ Copiar contenido literal (usar paráfrasis)
`,
  },
  {
    name: "api_client",
    description: `Make HTTP requests to REST APIs using curl-like methods (GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS)`,
    category: "api",
    version: "1.0.0",
    tools: ["api_request"],
    triggers: ["llama a la api","llama al api","consume la api","haz una petición","haz un request","envía un post","envía un put","envía un delete","curl","api request","rest api","endpoint","webhook","integrar con api","conectar con api","obtener datos de api","enviar datos a api"],
    body: `
# API Client Skill

## Cuándo se Activa

Esta skill se activa cuando el usuario necesita interactuar con una API REST: consultar datos, crear recursos, actualizar, eliminar, o cualquier operación HTTP.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`api_request\` | Realiza peticiones HTTP completas (GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS) con headers, body, query params y timeout | Siempre que necesites llamar un endpoint REST, webhook, o servicio externo |

## Parámetros de api_request

- \`method\` (requerido): GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS
- \`url\` (requerido): URL completa del endpoint
- \`headers\` (opcional): objeto con headers HTTP. Ej: \`{ "Authorization": "Bearer TOKEN", "Content-Type": "application/json" }\`
- \`body\` (opcional): cuerpo de la petición como string. Para JSON, enviar JSON.stringify(objeto)
- \`query_params\` (opcional): parámetros de query que se codificarán automáticamente en la URL
- \`timeout_ms\` (opcional): timeout en ms. Default: 30000. Máx: 120000

## Diferencia con web_fetch

- \`web_fetch\`: solo GET, sin headers custom, ideal para scraping de páginas web
- \`api_request\`: cualquier método HTTP, headers custom, body, query params — ideal para APIs REST

## Workflow

1. **Identificar endpoint y método** → Determinar URL, método, headers necesarios
2. **Construir request** → \`api_request({ method, url, headers, body })\`
3. **Validar respuesta** → Si 2xx: extraer datos. Si error: analizar y sugerir fix
4. **Presentar resultados** → JSON parseado en formato legible, no crudo a menos que se pida

## Mejores Prácticas

- Siempre enviar \`Content-Type: application/json\` cuando el body es JSON
- Usar \`query_params\` en lugar de append manual a la URL
- No exponer tokens/secrets en la respuesta final al usuario
- Si la API requiere auth, pedirla al usuario o usar variables de entorno
- Para errores 4xx, revisar: auth, formato del body, campos requeridos, rate limits

## Errores a Evitar

- ❌ Usar web_fetch para POST/PUT/DELETE con headers
- ❌ Enviar objetos directamente en body (debe ser string)
- ❌ Olvidar Content-Type al enviar JSON
- ❌ Exponer API keys en la respuesta visible
`,
  },
  {
    name: "capability_discovery",
    description: `Core discovery skill - find any capability with a single keyword`,
    category: "core",
    version: "1.2.0",
    tools: ["search_knowledge"],
    triggers: ["cómo busco herramientas","cómo encuentro skills","how to find tools","search knowledge","discovery","buscar en la base","encontrar herramientas"],
    body: `
# capability_discovery — Sistema de Discovery

Arrancás con 7 herramientas esenciales. Todo lo demás se descubre con **search_knowledge**.

## Regla de oro: UNA PALABRA, busca TODO

\`\`\`
search_knowledge(query="email")
\`\`\`

Eso solo — sin type, sin frases largas — devuelve tools, skills, MCP y playbook relacionados con "email".

**Evitá esto:** \`search_knowledge(type="tools", query="enviar correo electrónico")\` — el motor rankea por relevancia (BM25), así que una frase larga no falla, pero diluye el resultado: cada palabra de más sesga el ranking hacia coincidencias parciales y mezcla resultados menos relevantes.

**Preferí esto:** \`search_knowledge(query="email")\` — una palabra precisa da el resultado más ajustado y encuentra todo lo relacionado.

## Cuándo especificar type

Solo si querés filtrar resultados que ya son muchos:

\`\`\`
search_knowledge(query="email", type="mcp")   → solo herramientas externas de email
search_knowledge(query="email", type="tools") → solo herramientas nativas de email
\`\`\`

Por defecto type="all" — no hace falta especificarlo.

## Regla de prioridad

**Preferí herramientas nativas sobre MCP** cuando ambas sirven.
- Nativas: más rápidas, sin red, siempre disponibles
- MCP: cuando no hay equivalente nativo

## Flujo de uso

1. Identificá la palabra clave de lo que necesitás
2. \`search_knowledge(query="<palabra>")\` → resultados de todos los tipos
3. Cada resultado MCP incluye \`server_id\`; usalo para identificar la integración y buscar un especialista existente
4. Antes del primer uso de un servidor sin especialista, seguí el flujo de consentimiento del system prompt
5. Las tools encontradas se inyectan automáticamente en tu contexto para una ejecución directa solo cuando corresponda

---

## Ejemplos

\`\`\`
search_knowledge(query="pdf")       → tools para leer/escribir PDFs
search_knowledge(query="browser")   → tools de navegación web
search_knowledge(query="github")    → tools MCP de GitHub si están configuradas
search_knowledge(query="calendar")  → tools de Google Calendar
search_knowledge(query="A2UI")      → skills del panel interactivo
search_knowledge(query="slack")     → tools de Slack si están configuradas
\`\`\`
`,
  },
  {
    name: "a2ui_form",
    description: `Create rich interactive forms using A2UI v0.9 protocol with validation, data binding, and multi-step flows`,
    category: "a2ui",
    version: "1.0.0",
    tools: ["a2ui_create_surface","a2ui_update_components","a2ui_update_data_model","a2ui_delete_surface"],
    triggers: ["crear formulario A2UI","create A2UI form","formulario interactivo A2UI","A2UI form","pedir datos con A2UI","collect data A2UI","formulario con validación","form with validation","formulario multi-paso","multi-step form A2UI","form dinámico A2UI","dynamic form A2UI"],
    body: `
# A2UI Form Skill

## Cuándo se Activa

Para crear formularios interactivos ricos usando el protocolo A2UI v0.9. Usar cuando se necesita:
- Validación de campos (required, email, regex)
- Data binding dinámico
- Formularios multi-paso
- Choice pickers, sliders, checkboxes
- Formularios con acciones personalizadas

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`a2ui_create_surface\` | Crea la superficie A2UI | Siempre primero |
| \`a2ui_update_components\` | Envía componentes | Después de crear surface |
| \`a2ui_update_data_model\` | Actualiza datos | Para valores iniciales o dinámicos |
| \`a2ui_delete_surface\` | Elimina la superficie | Al terminar |

## Flujo Obligatorio

\`\`\`
1. a2ui_create_surface(surfaceId, catalogId, theme)
2. a2ui_update_components(surfaceId, components[])
3. a2ui_update_data_model(surfaceId, path, value)  // opcional, para datos iniciales
4. [esperar acción del usuario]
5. a2ui_delete_surface(surfaceId)  // al terminar
\`\`\`

## Componentes Disponibles

| Componente | Descripción | Props clave |
|------------|-------------|-------------|
| \`Column\` | Layout vertical | \`children\`, \`distribution\`, \`alignment\` |
| \`Row\` | Layout horizontal | \`children\`, \`distribution\`, \`alignment\` |
| \`Text\` | Texto | \`text\`, \`usageHint\` (h1-h5, body, caption, code) |
| \`Button\` | Botón | \`child\`, \`variant\`, \`action\` |
| \`TextField\` | Campo de texto | \`label\`, \`value\`, \`variant\` (shortText/longText/number/obscured), \`validationRegexp\`, \`checks\`, \`action\` |
| \`CheckBox\` | Checkbox | \`label\`, \`value\` |
| \`ChoicePicker\` | Selector múltiple | \`options\`, \`value\` (DynamicStringList), \`variant\` (mutuallyExclusive/multipleSelection), \`displayStyle\`, \`filterable\`, \`action\` |
| \`Slider\` | Slider numérico | \`value\`, \`minValue\`, \`maxValue\` |
| \`DateTimeInput\` | Fecha/hora | \`value\`, \`enableDate\`, \`enableTime\` |
| \`Card\` | Tarjeta | \`child\` |
| \`Divider\` | Separador | \`axis\` |
| \`Image\` | Imagen | \`url\`, \`fit\` |
| \`Tabs\` | Pestañas | \`tabItems\` |

## Data Binding

- Literal: \`"texto directo"\` o número
- Path: \`{ "path": "/form/name" }\` — se resuelve contra el data model
- Function call: \`{ "call": "formatDate", "args": {...} }\`

## Cuándo disparan acciones los inputs

| Componente | Cuándo dispara | Formato de action |
|------------|---------------|-------------------|
| \`Button\` | Al hacer click | \`{name: "...", context: {...}}\` o \`{event: {name: "...", context: {...}}}\` |
| \`TextField\` | Al perder foco (blur) o presionar Enter (en shortText) | \`{name: "...", context: {...}}\` |
| \`ChoicePicker\` | Inmediatamente al seleccionar/deseleccionar | \`{name: "...", context: {...}}\` |
| \`Slider\` | Al soltar el slider (onValueCommit) | \`{name: "...", context: {...}}\` |
| \`CheckBox\` | Al cambiar estado | — (solo two-way binding) |
| \`DateTimeInput\` | Al cambiar valor | — (solo two-way binding) |

**Nota**: Tanto \`{name: "...", context: {...}}\` (directo) como \`{event: {name: "...", context: {...}}}\` (con wrapper) son formatos válidos.

**Nota**: Para ChoicePicker usa siempre \`selections: {path: "..."}\` (no \`value\`) para two-way binding.

## Validación (checks)

\`\`\`json
"checks": [
  { "call": "required", "args": { "value": { "path": "/form/email" } }, "message": "Email is required" },
  { "call": "email", "args": { "value": { "path": "/form/email" } }, "message": "Invalid email" },
  { "call": "regex", "args": { "value": { "path": "/form/phone" }, "pattern": "^\\\\d{10}$" }, "message": "10 digits required" }
]
\`\`\`

## Ejemplo: Formulario de Contacto

\`\`\`json
// 1. Create surface
a2ui_create_surface(surfaceId: "contact_form", catalogId: "https://a2ui.org/specification/v0_9/basic_catalog.json", theme: {primaryColor: "#3B82F6", agentDisplayName: "Asistente"})

// 2. Send components
a2ui_update_components(surfaceId: "contact_form", components: [
  {"id": "root", "component": "Column", "children": ["header","name_field","email_field","msg_field","submit_btn"]},
  {id: "header", component: "Text", text: "Contacto", variant: "h2"},
  {id: "name_field", component: "TextField", label: "Nombre", value: {path: "/form/name"}, variant: "shortText"},
  {id: "email_field", component: "TextField", label: "Email", value: {path: "/form/email"}, variant: "shortText", validationRegexp: "^[^@]+@[^@]+\\\\.[^@]+$", checks: [{call: "required", args: {value: {path: "/form/email"}}, message: "Email obligatorio"}, {call: "email", args: {value: {path: "/form/email"}}, message: "Email inválido"}]},
  {id: "msg_field", component: "TextField", label: "Mensaje", value: {path: "/form/message"}, variant: "longText"},
  {id: "submit_label", component: "Text", text: "Enviar"},
  {id: "submit_btn", component: "Button", child: "submit_label", variant: "primary", action: {event: {name: "submit_contact", context: {name: {path: "/form/name"}, email: {path: "/form/email"}, message: {path: "/form/message"}}}}
])

// 3. Initialize data model
a2ui_update_data_model(surfaceId: "contact_form", path: "/form", value: {name: "", email: "", message: ""})
\`\`\`

## Mejores Prácticas

- Siempre incluir un componente \`root\` con id="root"
- Usar \`{ path: "/..." }\` para data binding en TextField values
- Agregar \`checks\` para validación de campos obligatorios
- Usar \`variant: "primary"\` para botones principales
- Eliminar surfaces con \`a2ui_delete_surface\` al terminar
- Usar formularios A2UI para toda captura estructurada de datos
`,
  },
  {
    name: "a2ui_dashboard",
    description: `Create real-time interactive dashboards using A2UI v0.9 protocol with dynamic data binding and live updates`,
    category: "a2ui",
    version: "1.0.0",
    tools: ["a2ui_create_surface","a2ui_update_components","a2ui_update_data_model","a2ui_delete_surface"],
    triggers: ["dashboard A2UI","panel de control A2UI","A2UI dashboard","mostrar métricas A2UI","A2UI metrics","dashboard interactivo A2UI","interactive dashboard","A2UI dashboard en tiempo real","real-time dashboard A2UI","mostrar datos A2UI","visualizar datos con A2UI"],
    body: `
# A2UI Dashboard Skill

## Cuándo se Activa

Para crear dashboards interactivos en tiempo real usando A2UI v0.9. Usar cuando se necesita:
- Métricas que se actualizan dinámicamente
- Dashboards con data binding
- Paneles con Cards, Rows, Columns
- Visualización de datos que cambia en tiempo real

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`a2ui_create_surface\` | Crea la superficie A2UI | Siempre primero |
| \`a2ui_update_components\` | Envía componentes | Para layout del dashboard |
| \`a2ui_update_data_model\` | Actualiza datos | Para métricas dinámicas |
| \`a2ui_delete_surface\` | Elimina la superficie | Al cerrar dashboard |

## Flujo Obligatorio

\`\`\`
1. a2ui_create_surface(surfaceId, catalogId, theme)
2. a2ui_update_components(surfaceId, components[])
3. a2ui_update_data_model(surfaceId, path, value)  // datos iniciales
4. [actualizar métricas con a2ui_update_data_model según necesidad]
5. a2ui_delete_surface(surfaceId)  // al terminar
\`\`\`

## Patrón de Dashboard Típico

\`\`\`json
[
  {"id": "root", "component": "Column", "children": ["title", "metrics_row", "tasks_list"]},
  {"id": "title", "component": "Text", "text": "Dashboard de Proyecto", "variant": "h1"},

  {"id": "metrics_row", "component": "Row", "children": ["card1", "card2", "card3"]},
  {"id": "card1", "component": "Card", "child": "card1_content", "weight": 1},
  {"id": "card1_content", "component": "Column", "children": ["card1_label", "card1_value"]},
  {"id": "card1_label", "component": "Text", "text": "Completado", "variant": "caption"},
  {"id": "card1_value", "component": "Text", "text": {"path": "/metrics/completionRate"}, "variant": "h2"},

  {"id": "tasks_list", "component": "List", "children": {"path": "/tasks", "componentId": "task_template"}},
  {"id": "task_template", "component": "Card", "child": "task_content"},
  {"id": "task_content", "component": "Column", "children": ["task_name", "task_status"]},
  {"id": "task_name", "component": "Text", "text": {"path": "/name"}},
  {"id": "task_status", "component": "Text", "text": {"path": "/status"}, "variant": "caption"}
]
\`\`\`

## Actualización en Tiempo Real

Para actualizar métricas específicas sin reenviar componentes:
\`\`\`json
a2ui_update_data_model(surfaceId: "dash", path: "/metrics/completionRate", value: 85)
a2ui_update_data_model(surfaceId: "dash", path: "/metrics/totalTasks", value: 24)
\`\`\`

Para reemplazar todo el data model:
\`\`\`json
a2ui_update_data_model(surfaceId: "dash", path: "/", value: {metrics: {completionRate: 90, totalTasks: 25}, tasks: [...]})
\`\`\`

## Mejores Prácticas

- Usar \`weight\` en Row/Column para proporciones (weight:1 vs weight:3 = 25% vs 75%)
- Agrupar métricas en Cards para separación visual
- Usar \`usageHint: "caption"\` para labels, \`"h1"/"h2"\` para valores
- Bind todos los valores dinámicos con \`{ path: "/..." }\`
- Actualizar métricas con \`a2ui_update_data_model\` path específico
- Eliminar surfaces al terminar para evitar memory leaks
`,
  },
  {
    name: "a2ui_interactive",
    description: `Create multi-step interactive workflows using A2UI v0.9 protocol with tabs, modals, choice pickers, and dynamic updates based on user actions`,
    category: "a2ui",
    version: "1.0.0",
    tools: ["a2ui_create_surface","a2ui_update_components","a2ui_update_data_model","a2ui_delete_surface"],
    triggers: ["interfaz interactiva A2UI","A2UI interactive UI","flujo A2UI","A2UI workflow","asistente A2UI","A2UI assistant","wizard A2UI","flujo multi-paso A2UI","multi-step flow A2UI","workflow interactivo","interactive workflow","asistente paso a paso","step-by-step assistant","A2UI con tabs y modales"],
    body: `
# A2UI Interactive Skill

## Cuándo se Activa

Para crear flujos interactivos multi-paso usando A2UI v0.9. Usar cuando se necesita:
- Wizards paso a paso
- Flujos de onboarding
- Asistentes de reserva/configuración
- Formularios con selections dinámicas
- Interacciones con modales de confirmación
- UIs que cambian según las acciones del usuario

## Herramientes Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`a2ui_create_surface\` | Crea la superficie A2UI | Siempre primero |
| \`a2ui_update_components\` | Envía/actualiza componentes | Para layout y cambios de UI |
| \`a2ui_update_data_model\` | Actualiza datos | Para estado del workflow |
| \`a2ui_delete_surface\` | Elimina la superficie | Al terminar flujo |

## Flujo Obligatorio

\`\`\`
1. a2ui_create_surface(surfaceId, catalogId, theme)
2. a2ui_update_components(surfaceId, components[])
3. a2ui_update_data_model(surfaceId, path, value)  // estado inicial
4. [recibir acción del usuario]
5. a2ui_update_data_model(...)  // actualizar estado con respuesta
6. a2ui_update_components(...)  // cambiar UI al siguiente paso
7. ... repetir 4-6 según necesidad ...
8. a2ui_delete_surface(surfaceId)  // al terminar
\`\`\`

## Patrones de Flujo Interactivo

### Wizard con Tabs (multi-paso)

\`\`\`json
[
  {id: "root", component: "Column", children: ["step_indicator", "tabs"]},
  {id: "step_indicator", component: "Text", text: {path: "/stepLabel"}, variant: "caption"},
  {id: "tabs", component: "Tabs", tabs: [
    {title: "Servicio", child: "step1"},
    {title: "Fecha", child: "step2"},
    {title: "Confirmar", child: "step3"}
  ]},
  {id: "step1", component: "Column", children: ["svc_label", "svc_picker"]},
  {id: "svc_label", component: "Text", text: "Seleccioná un servicio", variant: "h3"},
  {id: "svc_picker", component: "ChoicePicker", variant: "mutuallyExclusive", options: [...], value: {path: "/data/service"}},
  // ... más pasos
]
\`\`\`

### Confirmación con Modal

\`\`\`json
[
  {id: "confirm_modal", component: "Modal", trigger: "confirm_btn", content: "confirm_dialog"},
  {id: "confirm_btn", component: "Button", child: "confirm_btn_text", action: {}},
  {id: "confirm_btn_text", component: "Text", text: "Confirmar Reserva"},
  {id: "confirm_dialog", component: "Column", children: ["confirm_msg", "confirm_yes", "confirm_no"]},
  {id: "confirm_msg", component: "Text", text: "¿Confirmás tu reserva?"},
  {id: "confirm_yes", component: "Button", child: "yes_text", variant: "primary", action: {event: {name: "confirm_booking", context: {service: {path: "/data/service"}}}}},
  {id: "yes_text", component: "Text", text: "Sí, confirmar"},
  {id: "confirm_no", component: "Button", child: "no_text", variant: "borderless", action: {event: {name: "cancel"}}}},
  {id: "no_text", component: "Text", text: "Cancelar"}
]
\`\`\`

### Selección con ChoicePicker

\`\`\`json
[
  {id: "service_picker", component: "ChoicePicker",
    variant: "mutuallyExclusive",
    options: [
      {label: "Consulta General", value: "general"},
      {label: "Especializada", value: "specialized"},
      {label: "Urgencia", value: "urgent"}
    ],
    value: {path: "/data/serviceType"},
    action: {event: {name: "service_selected", context: {service: {path: "/data/serviceType"}}}}
  }
]
\`\`\`

## Mejores Prácticas

- Usar Tabs para wizards multi-paso
- Usar Modal para confirmaciones antes de acciones críticas
- Usar ChoicePicker con \`variant: "mutuallyExclusive"\` para selección única
- Mostrar indicador de progreso (paso X de Y)
- Actualizar data model después de cada acción del usuario
- Usar \`a2ui_update_components\` para cambiar la UI entre pasos
- Agregar validación con \`checks\` en TextField
- Mantener el estado del flujo en el data model (\`/data/step\`, \`/data/serviceType\`, etc.)
- Eliminar surfaces con \`a2ui_delete_surface\` al completar o cancelar
`,
  },
  {
    name: "image_editor",
    description: `Convertir, redimensionar y rotar imágenes con Bun.Image. Inspeccionar dimensiones y formato sin cargar la imagen al contexto.`,
    category: "images",
    version: "1.0.0",
    tools: ["image_metadata","image_transform","artifact_inspect"],
    triggers: ["convertí la imagen","convert image","redimensioná la imagen","resize image","achicá la foto","make it smaller","pasala a webp","convert to webp","rotá la imagen","rotate image","qué tamaño tiene","image dimensions","comprimí la imagen","compress image","hacé una miniatura","make a thumbnail"],
    body: `
# Image Editor Skill

## Cuándo se Activa

Cuando el usuario quiere **cambiar** una imagen (formato, tamaño, rotación) o
**saber** sus características. Corre sobre \`Bun.Image\`, nativo del runtime.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`image_metadata\` | Ancho, alto y formato | Siempre antes de transformar |
| \`image_transform\` | Convierte, redimensiona, rota | El trabajo en sí |
| \`artifact_inspect\` | Tipo MIME, integridad, tamaño | Cuando no está claro si el artefacto es una imagen |

## Lo Que Hay Que Entender

**Todo pasa por artefactos.** Una imagen no viaja en el mensaje: vive como
artefacto y se la nombra por su \`artifact_id\`. Es lo que evita que una foto de 4
MB entre a la ventana de contexto y se reenvíe en cada turno de la conversación.

**Transformar no destruye.** \`image_transform\` devuelve un artefacto **nuevo**.
El original sigue disponible, así que se puede probar un tamaño, ver que no
gustó y probar otro sin haber perdido nada.

**La proporción se pierde en silencio.** Si se pasan \`width\` y \`height\` juntos,
la imagen se estira sin avisar. Pasando uno solo, el otro se calcula.

## Formatos

\`jpeg\` · \`png\` · \`webp\` · \`avif\` · \`heic\`

Ante la duda, **webp**: pesa bastante menos que jpeg y png a calidad comparable,
y lo entienden todos los navegadores actuales.
`,
  },
  {
    name: "artifact_reader",
    description: `Leer archivos grandes que llegaron como artifact_ref: por tramos o buscando dentro, sin volcarlos enteros al contexto.`,
    category: "artifacts",
    version: "1.0.0",
    tools: ["artifact_read","artifact_inspect"],
    triggers: ["leé el archivo adjunto","read the attachment","qué dice el documento","what does the document say","buscá en el archivo","search in the file","artifact_ref","el resultado quedó truncado","the result was truncated","seguí leyendo","keep reading"],
    body: `
# Artifact Reader Skill

## Cuándo se Activa

Cuando aparece un **\`artifact_ref\`**: un archivo, un adjunto o el resultado de
una tool que era demasiado grande para entrar en el contexto.

## Herramientas Disponibles

| Tool | Qué hace | Cuándo usarla |
|------|----------|---------------|
| \`artifact_inspect\` | Tamaño, tipo MIME, integridad | Antes de leer, para decidir cómo |
| \`artifact_read\` | Contenido, por tramos o buscando | Para leer de verdad |

## Lo Que Hay Que Entender

**Un \`artifact_ref\` no es un error.** Es el mecanismo por el que un archivo
grande queda fuera de la ventana de contexto y a la vez disponible. El archivo
está entero; lo que cambia es que se lee a pedido en vez de entrar completo en
cada turno de la conversación.

**Buscar cuesta mucho menos que paginar.** \`artifact_read\` con \`search\` recorre
el archivo del lado del servidor y devuelve extractos de cada coincidencia con
su contexto alrededor. Paginar el mismo archivo con \`offset\`/\`limit\` gasta un
turno por tramo y mete en el contexto un montón de texto que no hacía falta.
Cuando se sabe qué se busca, se busca.

**Continuar es explícito.** Cada lectura devuelve \`next_offset\`. Ese es el valor
que se pasa para seguir — no se calcula a mano.
`,
  },
];
